"use client";
import { useEffect,useState } from "react";
import Image from "next/image";
import { Minus,Plus,Trash2,ShoppingBag,ArrowRight } from "lucide-react";
import { clearCart,readCart,removeFromCart,setQuantity,cartItemKey,type CartItem } from "@/lib/cart";
import { useRouter } from "next/navigation";
function money(n:number){return `₹${n.toLocaleString("en-IN")}`}
export default function CartPage(){
 const [items,setItems]=useState<CartItem[]>([]); const router=useRouter();
 useEffect(()=>{const sync=()=>setItems(readCart());sync();window.addEventListener("nagmeena-cart-change",sync);return()=>window.removeEventListener("nagmeena-cart-change",sync)},[]);
 const sync=()=>setItems(readCart());
 function change(item:CartItem,next:number){const key=cartItemKey(item);const r=setQuantity(key,next);sync();if(!r.ok&&r.reason==="max_stock")window.dispatchEvent(new CustomEvent("nagmeena-toast",{detail:{text:`Only ${item.variant?.stockQuantity ?? item.product.stockQuantity ?? 0} available in ${item.variant?.color||"this option"}.`,error:true}}));}
 return <main className="min-h-screen bg-base px-4 pb-16 pt-28 text-emerald sm:px-6"><div className="mx-auto max-w-5xl">
  <div className="mb-7"><p className="text-[10px] font-semibold uppercase tracking-[.25em] text-gold">NAGMEENA</p><h1 className="mt-1 font-heading text-3xl">Your Cart</h1><p className="mt-1 text-sm text-emerald/50">Review your suits before continuing to payment.</p></div>
  {!items.length?<div className="rounded-[30px] border border-emerald/10 bg-white/70 p-10 text-center shadow-xl"><ShoppingBag className="mx-auto text-gold" size={36}/><h2 className="mt-4 font-heading text-2xl">Your cart is empty</h2><button onClick={()=>router.push("/#collections")} className="mt-5 rounded-full bg-emerald px-5 py-3 text-sm font-semibold text-white">Continue Shopping</button></div>:<>
   <div className="space-y-3">{items.map(item=>{const {product,quantity,variant}=item;const key=cartItemKey(item);const max=Math.max(0,Number(variant?.stockQuantity ?? product.stockQuantity ?? 0));return <div key={key} className="flex gap-3 rounded-3xl border border-white/60 bg-white/70 p-3 shadow-sm sm:p-4"><div className="relative h-24 w-20 shrink-0 overflow-hidden rounded-2xl bg-[#eee7da] sm:h-28 sm:w-24">{product.images[0]&&<Image src={product.images[0].url} alt={product.name} fill sizes="96px" className="object-cover"/>}</div><div className="min-w-0 flex-1"><p className="font-heading text-lg">{product.name}</p><p className="text-xs text-emerald/45">{variant?.productCode || product.productCode}{variant?.color?` • ${variant.color}`:""}</p>{variant?.customCode&&<p className="mt-0.5 font-mono text-[10px] text-emerald/40">{variant.customCode}</p>}<p className="mt-2 font-semibold">{money(Number(product.price||0))}</p>{max<=0&&<p className="mt-1 text-xs font-semibold text-red-600">Out of Stock — remove this item before checkout.</p>}<div className="mt-2 flex items-center gap-2"><button onClick={()=>change(item,quantity-1)} className="rounded-full border p-1.5"><Minus size={13}/></button><span className="min-w-5 text-center text-sm">{quantity}</span><button onClick={()=>change(item,quantity+1)} disabled={quantity>=max||max<=0} className="rounded-full border p-1.5 disabled:opacity-35"><Plus size={13}/></button><button onClick={()=>{removeFromCart(key);sync()}} className="ml-auto rounded-full p-2 text-red-600" aria-label="Remove"><Trash2 size={15}/></button></div></div></div>})}</div>
   <div className="mt-5 flex flex-col gap-3 rounded-[30px] border border-emerald/10 bg-white/70 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs text-emerald/45">Total</p><p className="text-2xl font-semibold">{money(items.reduce((s,i)=>s+Number(i.product.price||0)*i.quantity,0))}</p></div><div className="flex gap-2"><button onClick={()=>{clearCart();sync()}} className="rounded-full border px-4 py-3 text-xs font-semibold">Clear</button><button onClick={()=>router.push("/buy-now?cart=1")} disabled={items.some(i=>(i.variant?.stockQuantity ?? i.product.stockQuantity ?? 0)<i.quantity)} className="inline-flex items-center justify-center gap-2 rounded-full bg-emerald px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue to Payment <ArrowRight size={15}/></button></div></div>
  </>}
 </div></main>
}
