"use client";
import { useEffect,useMemo,useState } from "react";
import Image from "next/image";
import { CheckCircle2,ChevronDown,Clock3,ExternalLink,Loader2,Mail,MapPin,RotateCcw,Search,Trash2,XCircle } from "lucide-react";

type Item={product_code:string;product_name:string;image_url?:string|null;quantity:number;unit_price:number;line_total:number;variant_product_code?:string|null;variant_custom_code?:string|null;variant_color?:string|null};
type Order={id:string;order_code:string;amount:number;status:string;customer_name?:string|null;customer_phone?:string|null;customer_email?:string|null;address?:string|null;city?:string|null;state?:string|null;pincode?:string|null;payment_reference?:string|null;proof_url?:string|null;created_at:string;return_action?:string|null;confirmation_email_sent_at?:string|null;confirmation_email_last_error?:string|null;items?:Item[]};
const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN")}`;

export default function AdminOrders({onNotify}:{onNotify:(type:"success"|"error",text:string)=>void}){
 const [orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[tab,setTab]=useState<"upcoming"|"accepted"|"rejected">("upcoming"),[updating,setUpdating]=useState<string|null>(null),[selected,setSelected]=useState<string[]>([]),[showMore,setShowMore]=useState(false),[search,setSearch]=useState(""),[returnOrder,setReturnOrder]=useState<Order|null>(null);
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/orders",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load orders.");setOrders(d.orders||[]);setSelected([]);}catch(e){onNotify("error",e instanceof Error?e.message:"Could not load orders.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const upcoming=orders.filter(o=>o.status==="verification_pending"),accepted=orders.filter(o=>o.status==="confirmed"),rejected=orders.filter(o=>o.status==="cancelled");
 const base=tab==="upcoming"?upcoming:tab==="accepted"?accepted:rejected;
 const searched=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return base;return base.filter(o=>[o.order_code,o.customer_name,o.customer_phone,o.customer_email,o.address,o.city,o.pincode,...(o.items||[]).flatMap(i=>[i.product_code,i.variant_product_code,i.variant_custom_code,i.variant_color,i.product_name])].filter(Boolean).join(" ").toLowerCase().includes(q));},[base,search]);
 const visible=showMore?searched:searched.slice(0,4);const now=new Date();const monthly=accepted.filter(o=>{const d=new Date(o.created_at);return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth();});const monthlyTotal=monthly.reduce((s,o)=>s+Number(o.amount||0),0);
 async function decide(id:string,status:"confirmed"|"cancelled"){setUpdating(id);try{const r=await fetch("/api/admin/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not update order.");setOrders(os=>os.map(o=>o.id===id?{...o,...d.order}:o));if(status==="confirmed"){const emailStatus=d.email?.status;const suffix=emailStatus==="sent"?" Confirmation email sent.":emailStatus==="not_provided"?" Customer did not provide email.":emailStatus==="not_configured"?" Email service not configured yet.":emailStatus==="failed"?" Order confirmed, but email failed.":"";onNotify("success",`Order accepted and confirmed.${suffix}`);}else onNotify("success","Order rejected and stock restored.");}catch(e){onNotify("error",e instanceof Error?e.message:"Could not update order.");}finally{setUpdating(null);}}
 async function retryEmail(id:string){setUpdating(id);try{const r=await fetch("/api/admin/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action:"resend_confirmation_email"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not send confirmation email.");setOrders(os=>os.map(o=>o.id===id?{...o,...d.order}:o));onNotify("success",d.email?.status==="already_sent"?"Confirmation email was already sent.":"Confirmation email sent.");}catch(e){onNotify("error",e instanceof Error?e.message:"Could not send confirmation email.");}finally{setUpdating(null);}}
 async function processReturn(action:"restock"|"delete"){if(!returnOrder)return;setUpdating(returnOrder.id);try{const r=await fetch("/api/admin/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:returnOrder.id,action:"return",returnAction:action})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not process return.");setOrders(os=>os.map(o=>o.id===returnOrder.id?{...o,...d.order}:o));setReturnOrder(null);onNotify("success",action==="restock"?"Return completed and stock restored.":"Return recorded without restocking.");}catch(e){onNotify("error",e instanceof Error?e.message:"Could not process return.");}finally{setUpdating(null);}}
 async function deleteSelected(){if(!selected.length||!window.confirm(`Delete ${selected.length} selected order(s)?`))return;try{const r=await fetch("/api/admin/orders",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:selected})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not delete orders.");setOrders(os=>os.filter(o=>!selected.includes(o.id)));setSelected([]);onNotify("success",`${d.deleted} order(s) deleted.`);}catch(e){onNotify("error",e instanceof Error?e.message:"Could not delete orders.");}}
 const allSelected=visible.length>0&&visible.every(o=>selected.includes(o.id));
 return <section className="mb-6 rounded-3xl border border-white/40 bg-white/45 p-4 shadow-[0_12px_40px_rgba(0,0,0,0.06)] backdrop-blur-xl sm:p-6">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-gold">Orders</p><h2 className="mt-1 font-heading text-xl">Order Management</h2><p className="mt-1 text-xs text-emerald/50">Completed payment submissions appear in Upcoming Orders.</p></div><button onClick={()=>void load()} className="w-full rounded-full border border-emerald/10 bg-white/70 px-3 py-2 text-[11px] font-semibold sm:w-auto">Refresh</button></div>
  <div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-white/60 p-3 sm:p-4"><p className="text-[9px] uppercase tracking-[.14em] text-emerald/40">Accepted this month</p><p className="mt-1 text-xl font-semibold sm:text-2xl">{monthly.length}</p></div><div className="rounded-2xl bg-white/60 p-3 sm:p-4"><p className="text-[9px] uppercase tracking-[.14em] text-emerald/40">Accepted value</p><p className="mt-1 text-xl font-semibold sm:text-2xl">{money(monthlyTotal)}</p></div></div>
  <div className="relative mt-4"><Search className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-emerald/40" size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setShowMore(false);}} placeholder="Search order, customer, pincode or product" className="field !pl-12 !pr-12 text-xs sm:text-sm"/>{search&&<button onClick={()=>setSearch("")} className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-emerald/50">Clear</button>}</div>
  <div className="mt-4 grid grid-cols-3 gap-2">{([['upcoming',`Upcoming (${upcoming.length})`],['accepted',`Accepted (${accepted.length})`],['rejected',`Rejected (${rejected.length})`]] as const).map(([value,label])=><button key={value} onClick={()=>{setTab(value);setShowMore(false);setSelected([]);}} className={`min-w-0 rounded-2xl border px-2 py-2 text-[10px] font-semibold leading-tight sm:rounded-full sm:px-3 sm:text-[11px] ${tab===value?"border-gold bg-gold/10 text-gold":"border-emerald/10 bg-white/60 text-emerald/60"}`}>{label}</button>)}</div>
  <div className="mt-3 flex items-center justify-between gap-3">{visible.length?<label className="flex items-center gap-2 text-[11px] font-semibold text-emerald/55"><input type="checkbox" checked={allSelected} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(o=>o.id)])]:selected.filter(id=>!visible.some(o=>o.id===id)))}/>Select visible</label>:<span/>}<button disabled={!selected.length} onClick={()=>void deleteSelected()} className="inline-flex items-center gap-1.5 rounded-full bg-red-600 px-3 py-2 text-[10px] font-semibold text-white disabled:opacity-35"><Trash2 size={13}/>Delete</button></div>
  {loading?<div className="flex justify-center py-10"><Loader2 className="animate-spin text-gold"/></div>:<div className="mt-4 space-y-3">{visible.map(o=>{const subtotal=(o.items||[]).reduce((s,i)=>s+Number(i.line_total||0),0),delivery=Math.max(0,Number(o.amount||0)-subtotal);return <article key={o.id} className={`overflow-hidden rounded-3xl border ${tab==="accepted"?"border-emerald/20 bg-emerald/5":tab==="rejected"?"border-red-200 bg-red-50":"border-emerald/10 bg-white/75"}`}><div className="p-4 sm:p-5"><div className="flex items-start gap-3"><input type="checkbox" className="mt-1 shrink-0" checked={selected.includes(o.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,o.id]:current.filter(id=>id!==o.id))}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="break-all font-mono text-xs font-semibold sm:text-sm">{o.order_code}</span><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${tab==="accepted"?"bg-emerald text-white":tab==="rejected"?"bg-red-600 text-white":"bg-gold/10 text-gold"}`}>{tab==="accepted"?"✓ Accepted":tab==="rejected"?(o.return_action?"Returned":"Rejected"):"New order"}</span></div>
   <div className="mt-3 grid gap-3 sm:grid-cols-[auto_1fr]">{o.items?.[0]?.image_url&&<div className="relative h-24 w-20 overflow-hidden rounded-2xl bg-[#eee7da]"><Image src={o.items[0].image_url} alt={o.items[0].product_name} fill sizes="80px" className="object-cover"/></div>}<div className="min-w-0"><p className="text-sm font-semibold leading-5">{o.items?.map(i=>`${i.product_name}${i.variant_color?` (${i.variant_color})`:""} ×${i.quantity}`).join(" • ")||"Order"}</p><div className="mt-2 grid grid-cols-2 gap-2 text-[11px]"><div className="rounded-xl bg-white/70 p-2"><span className="block text-emerald/40">Customer</span><b className="mt-0.5 block truncate">{o.customer_name||"Customer"}</b></div><div className="rounded-xl bg-white/70 p-2"><span className="block text-emerald/40">Mobile</span><b className="mt-0.5 block truncate">{o.customer_phone||"—"}</b></div></div></div></div>
   {(o.address||o.city||o.pincode)&&<div className="mt-3 flex items-start gap-2 rounded-2xl bg-white/65 p-3 text-[11px] leading-5 text-emerald/60"><MapPin size={14} className="mt-0.5 shrink-0 text-gold"/><span>{[o.address,o.city,o.state,o.pincode].filter(Boolean).join(", ")}</span></div>}
   <div className="mt-3 grid grid-cols-3 gap-2 text-center text-[10px] sm:text-[11px]"><div className="rounded-xl bg-white/65 p-2"><span className="block text-emerald/40">Subtotal</span><b>{money(subtotal)}</b></div><div className="rounded-xl bg-white/65 p-2"><span className="block text-emerald/40">Delivery</span><b>{delivery===0?"FREE":money(delivery)}</b></div><div className="rounded-xl bg-emerald p-2 text-white"><span className="block text-white/65">Total</span><b>{money(o.amount)}</b></div></div>
   {o.payment_reference&&<p className="mt-2 text-[11px] text-emerald/50">UTR: {o.payment_reference}</p>}{tab==="accepted"&&<div className="mt-2 flex flex-wrap items-center gap-2 text-[10px]"><span className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 font-semibold ${!o.customer_email?"border-emerald/10 bg-white text-emerald/45":o.confirmation_email_sent_at?"border-emerald/15 bg-emerald/5 text-emerald":"border-gold/20 bg-gold/5 text-gold"}`}><Mail size={11}/>{!o.customer_email?"Email not provided":o.confirmation_email_sent_at?"Email sent ✓":"Email pending"}</span>{o.confirmation_email_last_error&&!o.confirmation_email_sent_at&&<span className="max-w-full break-words text-red-600" title={o.confirmation_email_last_error}>Email error: {o.confirmation_email_last_error}</span>}</div>}<p className="mt-3 flex items-center gap-1 text-[10px] text-emerald/40"><Clock3 size={12}/>{new Date(o.created_at).toLocaleString("en-IN")}</p></div></div></div>
   <div className="grid grid-cols-2 gap-2 border-t border-emerald/8 bg-white/45 p-3 sm:flex sm:justify-end">{o.proof_url&&<a href={o.proof_url} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center justify-center gap-1.5 rounded-full border bg-white px-3 py-2 text-[11px] font-semibold"><ExternalLink size={13}/>Proof</a>}{tab==="upcoming"&&<><button disabled={updating===o.id} onClick={()=>void decide(o.id,"confirmed")} className="inline-flex min-h-10 items-center justify-center gap-1.5 rounded-full bg-emerald px-3 py-2 text-[11px] font-semibold text-white disabled:opacity-50"><CheckCircle2 size={13}/>Accept</button><button disabled={updating===o.id} onClick={()=>void decide(o.id,"cancelled")} className="col-span-2 inline-flex min-h-10 items-center justify-center gap-1.5 rounded-full bg-red-600 px-3 py-2 text-[11px] font-semibold text-white disabled:opacity-50 sm:col-auto"><XCircle size={13}/>Reject</button></>}{tab==="accepted"&&<>{o.customer_email&&!o.confirmation_email_sent_at&&<button disabled={updating===o.id} onClick={()=>void retryEmail(o.id)} className="inline-flex min-h-10 items-center justify-center gap-1.5 rounded-full border border-emerald/15 bg-white px-3 py-2 text-[11px] font-semibold text-emerald disabled:opacity-50"><Mail size={13}/>Retry Email</button>}<button disabled={updating===o.id} onClick={()=>setReturnOrder(o)} className="inline-flex min-h-10 items-center justify-center gap-1.5 rounded-full border border-gold/30 bg-gold/10 px-3 py-2 text-[11px] font-semibold text-gold"><RotateCcw size={13}/>Return</button></>}</div></article>})}
   {!visible.length&&<div className="rounded-2xl border border-dashed border-emerald/10 py-10 text-center text-sm text-emerald/45">No orders in this view.</div>}{searched.length>4&&<button onClick={()=>setShowMore(v=>!v)} className="mx-auto flex items-center gap-1.5 rounded-full border bg-white/70 px-4 py-2 text-xs font-semibold">{showMore?"Show less":"View more"}<ChevronDown size={14} className={showMore?"rotate-180":""}/></button>}</div>}
  {returnOrder&&<div className="fixed inset-0 z-[160] flex items-center justify-center bg-black/35 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><h3 className="font-heading text-2xl">Process return</h3><p className="mt-2 text-sm text-emerald/60">Choose what should happen to the returned item.</p><div className="mt-5 grid gap-3"><button disabled={updating===returnOrder.id} onClick={()=>void processReturn("restock")} className="rounded-2xl bg-emerald px-4 py-4 text-left text-sm font-semibold text-white">Restock item<span className="block text-xs font-normal text-white/75">Add the returned quantity back to inventory.</span></button><button disabled={updating===returnOrder.id} onClick={()=>void processReturn("delete")} className="rounded-2xl border border-red-200 bg-red-50 px-4 py-4 text-left text-sm font-semibold text-red-700">Delete / do not restock<span className="block text-xs font-normal text-red-600/70">Record the return without increasing stock.</span></button><button onClick={()=>setReturnOrder(null)} className="rounded-full border px-4 py-3 text-sm font-semibold">Cancel</button></div></div></div>}
 </section>;
}
