import { NextResponse } from "next/server";
export const runtime="nodejs"; export const dynamic="force-dynamic";
async function fetchJson(url:string,timeoutMs=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{signal:c.signal,headers:{"User-Agent":"NAGMEENA-store/1.0 (https://nagmeena.com)",Accept:"application/json"},cache:"no-store"});if(!r.ok)throw new Error(`Address service failed (${r.status})`);return await r.json();}finally{clearTimeout(t);}}
function cleanPin(v:unknown){return String(v||"").replace(/\D/g,"").slice(0,6);}
function uniqueMatches(rows:any[]){const seen=new Set<string>();return rows.filter(row=>{const k=`${row.pincode}|${String(row.name||"").toLowerCase()}|${String(row.district||"").toLowerCase()}`;if(!row.pincode||seen.has(k))return false;seen.add(k);return true;});}
async function cityViaPostalApi(city:string){try{const data=await fetchJson(`https://api.postalpincode.in/postoffice/${encodeURIComponent(city)}`),offices=Array.isArray(data?.[0]?.PostOffice)?data[0].PostOffice:[];return uniqueMatches(offices.map((o:any)=>({pincode:cleanPin(o.Pincode),name:o.Name||"",district:o.District||o.Division||"",state:o.State||""})).filter((o:any)=>/^\d{6}$/.test(o.pincode)));}catch{return [];}}
async function cityViaNominatim(city:string){try{const data=await fetchJson(`https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=in&addressdetails=1&limit=12&q=${encodeURIComponent(`${city}, India`)}`);if(!Array.isArray(data))return[];return uniqueMatches(data.map((entry:any)=>{const a=entry?.address||{};return{pincode:cleanPin(a.postcode),name:a.suburb||a.neighbourhood||a.village||a.town||a.city||entry?.name||"",district:a.city_district||a.state_district||a.county||a.city||a.town||"",state:a.state||""};}).filter((o:any)=>/^\d{6}$/.test(o.pincode)));}catch{return[];}}
async function reverseLocation(lat:number,lon:number){const data=await fetchJson(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${encodeURIComponent(String(lat))}&lon=${encodeURIComponent(String(lon))}&addressdetails=1&zoom=18`,10000),a=data?.address||{};return{address:[a.house_number,a.road,a.neighbourhood||a.suburb||a.quarter||a.village].filter(Boolean).join(", "),city:a.city||a.town||a.village||a.municipality||a.county||"",district:a.city_district||a.state_district||a.county||"",state:a.state||"",pincode:cleanPin(a.postcode),display_name:data?.display_name||""};}
export async function GET(request:Request){const u=new URL(request.url),pincode=cleanPin(u.searchParams.get("pincode")),city=(u.searchParams.get("city")||"").trim().slice(0,80),lat=Number(u.searchParams.get("lat")),lon=Number(u.searchParams.get("lon"));try{if(pincode&&/^\d{6}$/.test(pincode)){const data=await fetchJson(`https://api.postalpincode.in/pincode/${encodeURIComponent(pincode)}`),offices=Array.isArray(data?.[0]?.PostOffice)?data[0].PostOffice:[];if(!offices.length)return NextResponse.json({error:"We could not find this pincode."},{status:404});const first=offices[0];return NextResponse.json({pincode,city:first.District||first.Division||first.Name||"",district:first.District||first.Division||"",state:first.State||"",areas:[...new Set(offices.map((o:any)=>o.Name).filter(Boolean))].slice(0,16)});}if(city.length>=3){const primary=await cityViaPostalApi(city),fallback=primary.length>=5?[]:await cityViaNominatim(city);return NextResponse.json({matches:uniqueMatches([...primary,...fallback]).slice(0,16)});}if(Number.isFinite(lat)&&Number.isFinite(lon)&&Math.abs(lat)<=90&&Math.abs(lon)<=180){const result=await reverseLocation(lat,lon);if(result.pincode&&/^\d{6}$/.test(result.pincode)){try{const pinData=await fetchJson(`https://api.postalpincode.in/pincode/${encodeURIComponent(result.pincode)}`),offices=Array.isArray(pinData?.[0]?.PostOffice)?pinData[0].PostOffice:[],first=offices[0];if(first){result.city=result.city||first.District||first.Division||first.Name||"";result.district=result.district||first.District||first.Division||"";result.state=result.state||first.State||"";}}catch{}}return NextResponse.json(result);}return NextResponse.json({error:"Provide a pincode, city or coordinates."},{status:400});}catch(error){console.error("[location]",error);return NextResponse.json({error:"Address lookup is temporarily unavailable. You can still enter the address manually."},{status:503});}}
